# Generated by Django 3.0.5 on 2020-04-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=16, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('total_des_depenses', models.PositiveIntegerField(default=0, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_pcs', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('montant_total', models.PositiveIntegerField(blank=True, default=0.0, null=True)),
                ('remise', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('somme_finale', models.PositiveIntegerField(blank=True, default=0.0, null=True)),
                ('statut', models.CharField(blank=True, choices=[('Payé', 'Payé'), ('Impayé', 'Impayé')], default='Payé', max_length=8, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True, unique=True)),
                ('quantite', models.PositiveIntegerField(null=True)),
                ('prix', models.PositiveIntegerField(null=True)),
                ('remise', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prix_final', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Category')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True, unique=True)),
                ('taille', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='XS', max_length=6, null=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Order')),
                ('stock', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Stock')),
            ],
        ),
    ]
